name: "Azure DevOps NPM"
description: Setup .npmrc file for Azure DevOps"
branding:
    icon: "align-justify"
    color: "orange"
inputs:
    organisation:
        description: "Your Azure organisation"
        required: true
    project:
        description: "Your Azure project"
        required: false
    registry:
        description: "Your Azure registry"
        required: true
    user:
        description: "Your Azure user"
        required: true
    password:
        description: "Your Azure password"
        required: true
    email:
        description: "Your Azure email"
        required: true
    scope:
        description: "Your package scope"
        required: false
    encode_password:
        description: Encode the given password to base64
        required: false
        default: "false"
runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - "--organisation"
        - ${{ inputs.organisation }}
        - "--project"
        - ${{ inputs.project }}
        - "--registry"
        - ${{ inputs.registry }}
        - "--user"
        - ${{ inputs.user }}
        - "--password"
        - ${{ inputs.password }}
        - "--encode_password"
        - ${{ inputs.encode_password }}
        - "--email"
        - ${{ inputs.email }}
        - "--scope"
        - ${{ inputs.scope }}